// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEKGLv9GE_JIQqHwzU8geQ0qTUDT9tFkI',
    appId: '1:382578261018:web:768fb8b70339e6ed5ae5a3',
    messagingSenderId: '382578261018',
    projectId: 'crud-videojuegos-final',
    authDomain: 'crud-videojuegos-final.firebaseapp.com',
    storageBucket: 'crud-videojuegos-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-awcH_E26_pbdtnEpBnFfp8XMUW3lJaU',
    appId: '1:382578261018:android:72c1dc17349bd7b75ae5a3',
    messagingSenderId: '382578261018',
    projectId: 'crud-videojuegos-final',
    storageBucket: 'crud-videojuegos-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkSDCjYy9pAeyByqegeCtZ4pwAdeS4wXk',
    appId: '1:382578261018:ios:d7e994e36c4b3a845ae5a3',
    messagingSenderId: '382578261018',
    projectId: 'crud-videojuegos-final',
    storageBucket: 'crud-videojuegos-final.firebasestorage.app',
    iosBundleId: 'com.example.flCrudVideojuegosDpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkSDCjYy9pAeyByqegeCtZ4pwAdeS4wXk',
    appId: '1:382578261018:ios:d7e994e36c4b3a845ae5a3',
    messagingSenderId: '382578261018',
    projectId: 'crud-videojuegos-final',
    storageBucket: 'crud-videojuegos-final.firebasestorage.app',
    iosBundleId: 'com.example.flCrudVideojuegosDpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEKGLv9GE_JIQqHwzU8geQ0qTUDT9tFkI',
    appId: '1:382578261018:web:fc103190f1cf2dbb5ae5a3',
    messagingSenderId: '382578261018',
    projectId: 'crud-videojuegos-final',
    authDomain: 'crud-videojuegos-final.firebaseapp.com',
    storageBucket: 'crud-videojuegos-final.firebasestorage.app',
  );

}