// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI6K802NDgqVkY0S2AYS_XsUeFixVJQD4',
    appId: '1:74789784936:web:4fd77ea15ff32528dc1add',
    messagingSenderId: '74789784936',
    projectId: 'fluttergames-da248',
    authDomain: 'fluttergames-da248.firebaseapp.com',
    storageBucket: 'fluttergames-da248.firebasestorage.app',
    measurementId: 'G-F6M4856EXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVtjVNBo854-eH1btShG3IFVYjm-q7hRs',
    appId: '1:74789784936:android:c369e775ee8a0f05dc1add',
    messagingSenderId: '74789784936',
    projectId: 'fluttergames-da248',
    storageBucket: 'fluttergames-da248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2GX9ymE97pi6zfRCGkxkXf_ePustvZMQ',
    appId: '1:74789784936:ios:44dc4ee38c38f57adc1add',
    messagingSenderId: '74789784936',
    projectId: 'fluttergames-da248',
    storageBucket: 'fluttergames-da248.firebasestorage.app',
    iosBundleId: 'com.example.flCrudVideojuegosDpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2GX9ymE97pi6zfRCGkxkXf_ePustvZMQ',
    appId: '1:74789784936:ios:44dc4ee38c38f57adc1add',
    messagingSenderId: '74789784936',
    projectId: 'fluttergames-da248',
    storageBucket: 'fluttergames-da248.firebasestorage.app',
    iosBundleId: 'com.example.flCrudVideojuegosDpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI6K802NDgqVkY0S2AYS_XsUeFixVJQD4',
    appId: '1:74789784936:web:5fc362c2e968a5a4dc1add',
    messagingSenderId: '74789784936',
    projectId: 'fluttergames-da248',
    authDomain: 'fluttergames-da248.firebaseapp.com',
    storageBucket: 'fluttergames-da248.firebasestorage.app',
    measurementId: 'G-P79X2KSEJ9',
  );
}
